In [ ]:
# Import pakietów i załadowanie danych

import pandas as pd
from bokeh.plotting import figure, output_file, show, ColumnDataSource, reset_output
from bokeh.io import show
from bokeh.layouts import column, row
from bokeh.models import Select, CustomJS, Slider, PreText, CheckboxGroup


df = pd.read_excel('../data/raw/2023_PM10_1g.xlsx')

In [9]:
# Filtracja danych

top_10_columns_sorted = df.isnull().sum().sort_values(ascending=False).head(10)
filtered_df = df[list(top_10_columns_sorted.index)]

In [10]:
filtered_df

,WpPoznDabrow,LdPioTrKraPr,LdLodzGdansk,LdPabiKonsta,MpKrakOsPias,PmSlupKniazi,SkKielJurajs,WpKoscianMayMOB,WmOstrPilsud,PdBialAlPils
0,29.70770,33.630,61.0134,27.8720,263.9650,11.0000,15.3,NaN,25.0195,NaN
1,8.76267,21.090,42.6258,17.8720,154.5990,11.2466,45.6,NaN,11.0414,11.9350
2,7.62683,18.924,8.2187,13.8720,54.7269,13.2020,41.1,NaN,13.0984,9.9018
3,7.65438,17.898,6.8257,8.8720,40.8342,13.6077,29.6,NaN,13.2797,10.4998
4,8.29311,12.654,NaN,10.8720,44.7827,14.7940,22.1,NaN,14.2086,12.1742
...,...,...,...,...,...,...,...,...,...,...
8755,14.76190,NaN,11.0047,25.3667,24.1855,12.0132,29.4,52.6577,27.9904,34.0000
8756,15.25460,NaN,15.1837,26.3097,37.9393,23.9849,29.8,67.8074,36.1303,31.9000
8757,15.79550,NaN,34.8250,32.9107,31.8240,14.2802,30.3,64.0395,28.4964,21.9000
8758,16.63970,NaN,45.5511,19.7087,34.0463,34.7751,33.4,65.2450,44.7064,18.9000
8759,18.48230,NaN,18.1090,28.1957,43.8098,18.9828,36.1,56.4299,30.8568,17.6000

In [ ]:
# Reload the original dataset
df = pd.read_excel('../data/raw/2023_C6H6_1g.xlsx', header=None)

# Remove rows 0, 2, 3, 4, 5
df = df.drop(index=[0, 2, 3, 4, 5])

# Set row 1 as column names and reset the DataFrame
df.columns = df.iloc[0]
df = df[1:].reset_index(drop=True)

# Set the datetime column as index and convert to datetime format
df = df.set_index(df.columns[0])
df.index = pd.to_datetime(df.index, errors='coerce')

1,DsJelGorOgin,DsLegAlRzecz,DsWalbrzWyso,DsWrocWybCon,DsZgorBohGet,KpBydPlPozna,KpNaklWawrzy,KpSwiecJPawlMOB,KpToruKaszow,KpWloclOkrze,...,SlZlotPotLes,SlZywieKoper,WmElbBazynsk,WmElkStadion,WmOlsPuszkin,WpKaliSawick,WpKoniWyszyn,WpKozieosLes,ZpSzczecPrze,ZpSzczPilsud
Kod stacji,,,,,,,,,,,,,,,,,,,,,
2023-01-01 01:00:00,0.14732,1.2505,0.17393,0.33435,NaN,0.6,0.3,0.7,2.1,1.1,...,0.84466,0.69309,0.94958,1.71585,2.93343,0.1,NaN,0.21688,0.58219,0.48303
2023-01-01 02:00:00,0.12078,0.62424,0.15919,0.29169,NaN,0.7,0.3,0.4,2.5,1,...,0.68119,0.61209,1.03093,1.39422,0.80464,0.14058,NaN,0.25553,0.50241,0.51615
2023-01-01 03:00:00,0.11809,0.51921,0.52612,0.21753,NaN,0.6,0.2,0.5,5.1,1,...,0.63599,0.55431,0.57889,1.31936,0.60581,0.11,NaN,0.21297,0.43019,0.47502
2023-01-01 04:00:00,0.12125,0.44429,0.23165,0.21294,NaN,0.6,0.2,0.4,9.7,0.8,...,0.68338,0.56808,0.38609,1.24819,0.63377,0.18,NaN,0.15405,0.39239,0.41679
2023-01-01 05:00:00,0.12439,0.35073,0.08777,0.1458,NaN,0.5,0.2,0.4,3.2,0.7,...,0.63673,0.48492,0.39262,1.12414,0.58645,0.10192,NaN,0.13168,0.41877,0.37629
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-12-31 20:00:00,0.84819,4.99709,1.32579,2.8674,1.28102,2.7,4,2.2,2.5,3.7,...,1.51751,NaN,0.98635,0.86777,0.69313,0.74361,2.42469,1.83098,1.79597,1.6362
2023-12-31 21:00:00,0.56021,7.81015,0.77418,3.20589,1.22823,2.4,3.2,1.7,2.1,3.4,...,1.62588,NaN,0.82447,0.7289,0.76095,0.60639,2.39214,1.96475,1.73932,1.61163
2023-12-31 22:00:00,0.49773,7.59415,1.2492,2.88144,1.27912,2.4,3.6,1.1,1.9,2.9,...,1.67544,NaN,0.81397,0.93077,0.6546,0.64458,2.43278,1.9944,2.04257,1.73394
2023-12-31 23:00:00,0.62982,5.75056,0.90018,3.19095,1.35635,2.3,3.1,1.1,2,3.2,...,1.77553,NaN,0.83709,1.19308,0.9084,0.60403,2.54584,1.982,2.36906,1.75041
2024-01-01 00:00:00,1.26158,7.37952,1.29942,3.57795,1.16532,2.3,3.2,1.1,2.2,2.9,...,1.78286,NaN,0.85391,1.26822,0.57417,0.65111,2.66378,1.96819,2.41129,1.80495

In [20]:
df[0]

KeyError: 0